chore(action): Add action for push new banlist to evolution bsnlist repo

diff --git a/.github/workflows/mercury-lflist-sync.yml b/.github/workflows/mercury-lflist-sync.yml
--- a/.github/workflows/mercury-lflist-sync.yml
+++ b/.github/workflows/mercury-lflist-sync.yml
@@ -13,13 +13,13 @@ jobs:
       - uses: poll-github-repo/action@v1
         id: check
         with:
-          repo-to-sync: fallenstardust/YGOMobile-cn-ko-en
+          repo-to-sync: diegofcornejo/YGOMobile-cn-ko-en
           path-to-sync: mobile/assets/data/conf/lflist.conf
           cache-path: .sync/mercury-lflist-sync
           tracking-issue-label: upstream-mercury-lflist
           tracking-issue-title: "Update on {{ path }}: {{ sha-short }}"
           tracking-issue-body: |
-            New commit in fallenstardust/YGOMobile-cn-ko-en:
+            New commit in diegofcornejo/YGOMobile-cn-ko-en:
 
             **{{ message }}** [link]({{ url }})
           token: ${{ secrets.GH_TOKEN }}
@@ -69,13 +69,13 @@ jobs:
           name: koishi-files
           path: koishi/
 
-      - name: Upload Project Iginis artifacts
+      - name: Upload Project Ignis artifacts
         uses: actions/upload-artifact@v4
         with:
-            name: projectignis-files
-            path: projectignis/
+          name: projectignis-files
+          path: projectignis/
   
-  hash:
+  process:
     name: Process LFLIST
     needs: download
     runs-on: ubuntu-latest
@@ -245,3 +245,72 @@ jobs:
 
       - name: List files in new directory
         run: ls -l new
+
+      - name: Upload new artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: new-files
+          path: new/
+
+  update:
+    name: Update LFLIST
+    needs: process
+    runs-on: ubuntu-latest
+    steps:
+      - name: Download new artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: new-files
+          path: new/
+
+      - name: Commit and push changes
+        run: |
+          # Configuration variables
+          REPO_URL="https://github.com/diegofcornejo/evolution-server-lflist.git"
+          BRANCH="main"
+          ORIGIN_REPO="diegofcornejo/YGOMobile-cn-ko-en"
+          FILE_PATH="mobile/assets/data/conf/lflist.conf"
+          COMMIT_MESSAGE="Update banlists with new KS lists"
+
+          # Get the SHA of the latest commit that modified the target file from the origin repository
+          LATEST_COMMIT_SHA=$(curl -s "https://api.github.com/repos/$ORIGIN_REPO/commits?path=$FILE_PATH&per_page=1" | jq -r '.[0].sha')
+
+          # Check if the SHA was successfully retrieved
+          if [ "$LATEST_COMMIT_SHA" == "null" ] || [ -z "$LATEST_COMMIT_SHA" ]; then
+            echo "Error: Unable to retrieve the latest commit SHA for $FILE_PATH from $ORIGIN_REPO."
+            exit 1
+          fi
+
+          COMMIT_MESSAGE="$COMMIT_MESSAGE - based on $LATEST_COMMIT_SHA"
+          echo "Commit message: $COMMIT_MESSAGE"
+
+          # Ensure the new directory exists and has files
+          if [ -d "new" ] && [ "$(ls -A new)" ]; then
+            # Clone the remote repository
+            git clone $REPO_URL repo
+
+            # Copy the new files to the cloned repository
+            cp -R new/* repo/
+
+            # Change to the repository directory
+            cd repo
+
+            # Set git user configuration
+            git config user.name "Evolution Bot"
+            git config user.email "bot@evolutionygo.com"
+
+            # Add new files to the repository
+            git add .
+
+            # Commit the changes
+            git commit -m "$COMMIT_MESSAGE"
+
+            # Pull the latest changes to avoid conflicts
+            git pull origin $BRANCH --rebase
+
+            # Push the changes to the remote repository
+            git push origin $BRANCH
+
+          else
+            echo "No files to commit in the 'new' directory."
+          fi
